"""
Django settings for jaspers_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m5@u^m7p-fh7m5jbq(5dkoe-uqgkmcb@p_zq^79n!_3c@r+*#s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '..', 'frontend'),
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   
    'corsheaders',      
    'jaspers_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jaspers_backend.urls'
# --- Beveiligingsinstellingen ---
# ALLOWED_HOSTS: Lijst van host/domeinnamen waarvoor deze Django-site mag dienen.
# Dit is essentieel om de DisallowedHost fout te voorkomen.
ALLOWED_HOSTS = [
    '192.168.1.161', # Jouw lokale IP-adres is toegevoegd
    'localhost',     # Voor lokale ontwikkeling via http://localhost
    '127.0.0.1',     # Standaard localhost IP
    # Voeg hier eventueel andere domeinnamen toe wanneer je app live gaat (bijv. 'jouwdomein.com')
]

# --- CORS Headers Configuratie ---
# CORS_ALLOWED_ORIGINS: Specificeert welke frontend origins (protocollen, hosts, poorten)
# zijn toegestaan om cross-origin requests te doen naar je Django-backend.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",          # Frontend draait op 8000
    "http://192.168.1.161:8000",      # Frontend draait op 8000
    # Voeg hier eventueel andere URLs toe zodra je app live gaat (bijv. "https://jouwdomein.com")
]

# CORS_ALLOW_METHODS: Geeft aan welke HTTP-methoden zijn toegestaan voor cross-origin requests.
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'POST',
    'PUT',
]

# CORS_ALLOW_CREDENTIALS: Sta het versturen van credentials (cookies, auth headers) toe bij cross-origin requests.
# Dit is vaak nodig als je authenticatie of CSRF-tokens gebruikt.
CORS_ALLOW_CREDENTIALS = True 

# --- CSRF Configuratie voor AJAX / Frontend ---
# CSRF_COOKIE_NAME: De naam van de cookie die het CSRF-token bevat.
CSRF_COOKIE_NAME = "csrftoken"
# CSRF_TRUSTED_ORIGINS: Lijst van origins die als "vertrouwd" worden beschouwd voor CSRF-doeleinden.
# BELANGRIJK: De waarden moeten beginnen met een schema (http:// of https://).
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.1.161", # Jouw IP-adres (zonder poort)
    "http://localhost",     # Voor localhost (zonder poort)
    # Voeg hier ook je productiedomeinen toe, inclusief schema
]

# CSRF_COOKIE_HTTPONLY: Voorkomt dat JavaScript het CSRF-cookie leest. Voor debugging kun je dit op False zetten,
# maar voor productie is True veiliger. We zetten hem op False om JS toegang te geven voor de fetch.
CSRF_COOKIE_HTTPONLY = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jaspers_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# E-mail instellingen voor het versturen van berichten
# Dit zijn de basisinstellingen voor de meeste SMTP-servers (zoals Gmail, Outlook, etc.)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Bijvoorbeeld 'smtp.gmail.com' of 'smtp.mail.com'
EMAIL_PORT = 587  # Dit is de standaard poort voor TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jdelaat1@gmail.com'
EMAIL_HOST_PASSWORD = 'dckj hnpk msya lqcm' # Let op: gebruik een app-wachtwoord voor Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'jaspers_app' / 'static', # <-- Zorg dat deze regel er is
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True