# Generated by Django 5.2.5 on 2025-08-20 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursus', models.CharField(blank=True, max_length=200, null=True)),
                ('cursusdatum', models.DateField(blank=True, null=True)),
                ('refresher', models.BooleanField(default=False)),
                ('geldigheid_jaren', models.CharField(blank=True, max_length=50, null=True)),
                ('geldigheid_datum', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deelnemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanhef', models.CharField(blank=True, max_length=5, null=True)),
                ('voornaam', models.CharField(blank=True, max_length=100, null=True)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=50, null=True)),
                ('achternaam', models.CharField(blank=True, max_length=100, null=True)),
                ('bedrijfsnaam', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('windaId', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cursus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deelnemers', to='jaspers_app.cursus')),
            ],
        ),
    ]
