# Generated by Django 5.2.5 on 2025-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deelnemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanhef', models.CharField(blank=True, max_length=5)),
                ('voornaam', models.CharField(max_length=100)),
                ('tussenvoegsel', models.CharField(blank=True, max_length=50)),
                ('achternaam', models.CharField(max_length=100)),
                ('bedrijfsnaam', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('geboortedatum', models.DateField(blank=True, null=True)),
                ('refresher', models.BooleanField(default=False)),
                ('cursus', models.CharField(max_length=200)),
                ('cursusdatum', models.DateField()),
                ('geldigheid', models.CharField(max_length=50)),
                ('winda_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
