# Generated by Django 5.2.5 on 2025-08-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursus',
            options={'verbose_name_plural': 'Cursussen'},
        ),
        migrations.AlterModelOptions(
            name='deelnemer',
            options={'verbose_name_plural': 'Deelnemers'},
        ),
    ]
