# Generated by Django 5.2.5 on 2025-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deelnemer',
            constraint=models.UniqueConstraint(fields=('voornaam', 'achternaam', 'geboortedatum'), name='unieke_deelnemer_constraint'),
        ),
    ]
