# Generated by Django 5.2.5 on 2025-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0002_deelnemer_delete_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deelnemer',
            old_name='winda_id',
            new_name='windaId',
        ),
        migrations.RemoveField(
            model_name='deelnemer',
            name='geldigheid',
        ),
        migrations.AddField(
            model_name='deelnemer',
            name='geldigheid_jaren',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='cursusdatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
