# Generated by Django 5.2.5 on 2025-08-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0003_rename_winda_id_deelnemer_windaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deelnemer',
            name='geldigheid_datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='bedrijfsnaam',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='cursus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='tussenvoegsel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='voornaam',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
