# Generated by Django 5.2.5 on 2025-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0004_deelnemer_geldigheid_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deelnemer',
            name='aanhef',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='achternaam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='cursus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='geldigheid_jaren',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='voornaam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deelnemer',
            name='windaId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
