# Generated by Django 5.2.5 on 2025-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaspers_app', '0005_alter_deelnemer_aanhef_alter_deelnemer_achternaam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deelnemer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
